sudo: required

services:
  - docker

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

install:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then \
      sudo docker build --build-arg CI=true -t ubuntu/mantella:latest . && \
      sudo docker run -v ${TRAVIS_BUILD_DIR}:/mantella -w /mantella --name mantella -t -d ubuntu/mantella && \
      sudo docker exec mantella chmod a+x ./.develop.sh \
    ; fi
  - | 
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then \
      wget -O catch.tar.gz https://github.com/philsquared/Catch/archive/V1.5.0.tar.gz && \
      mkdir catch && \
      tar -xzf catch.tar.gz -C ./catch --strip-components=1 && \
      sudo cp catch/single_include/catch.hpp /usr/local/include/ && \
      rm -Rf catch.tar.gz catch/ && \
      chmod a+x ./.develop.sh \
    ; fi
  
addons:
  coverity_scan:
    project:
      name: "SebastianNiemann/Mantella"
    notification_email: niemann@sra.uni-hannover.de
    build_command_prepend: cov-configure --compiler gcc-5 --template
    build_command: sudo docker exec mantella /bin/bash -c "./.develop.sh --test --install"
    branch_pattern: coverity_scan

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo docker exec mantella /bin/bash -c "./.develop.sh --test --install"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./.develop.sh --test --install /usr/local/include; fi

before_deploy:
     # As Travis does not support defining Bash variables within the *deploy* command, this is done at an earlier stage.
  -  'COMMIT_MESSAGE="autodoc : $(git log --pretty="%s - %an" -1)"'
  
deploy:
  skip_cleanup: true
  provider: script
  on:
    condition: "$CC = gcc && $TRAVIS_OS_NAME = linux"
    branch: master 
  script: sudo docker exec mantella /bin/bash -c "./.develop.sh --doc"; openssl aes-256-cbc -K $encrypted_f98812e554e5_key -iv $encrypted_f98812e554e5_iv -in ./doc/docsecret.enc -out ./doc/docsecret -d; chmod 400 ./doc/docsecret; ssh-agent bash -c 'ssh-add ./doc/docsecret; git clone --branch master --depth 1 git@github.com:Mantella/Mantella.info.git'; cp -r ./doc/_html/* ./Mantella.info/; cd Mantella.info/; git add -A; git commit -m "${COMMIT_MESSAGE}"; ssh-agent bash -c 'ssh-add ../doc/docsecret; git push origin master';