sudo: required

services:
  - docker

language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

install:
  - sudo docker build -t ubuntu/mantella:latest .
  - sudo docker run -v ${TRAVIS_BUILD_DIR}:/mantella -w /mantella --name mantella -t -d ubuntu/mantella
  - sudo docker exec mantella chmod a+x ./.develop.sh
  
addons:
  coverity_scan:
    project:
      name: "SebastianNiemann/Mantella"
    notification_email: niemann@sra.uni-hannover.de
    build_command_prepend: cov-configure --compiler gcc-5 --template
    build_command: sudo docker exec mantella /bin/bash -c "./.develop.sh --test --install"
    branch_pattern: coverity_scan

script:
  - sudo docker exec mantella /bin/bash -c "./.develop.sh --test --install"
