sudo: required

services:
  - docker

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo docker build -t ubuntu/mantella:latest .; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo docker run -v ${TRAVIS_BUILD_DIR}:/mantella -w /mantella --name mantella -t -d ubuntu/mantella; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo docker exec mantella chmod a+x ./.develop.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install cmake catch; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then chmod a+x ./.develop.sh; fi
  
addons:
  coverity_scan:
    project:
      name: "SebastianNiemann/Mantella"
    notification_email: niemann@sra.uni-hannover.de
    build_command_prepend: cov-configure --compiler gcc-5 --template
    build_command: sudo docker exec mantella /bin/bash -c "./.develop.sh --test --install"
    branch_pattern: coverity_scan

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo docker exec mantella /bin/bash -c "./.develop.sh --test --install"; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./.develop.sh --test --install; fi
