image: Visual Studio 2015
platform:
  - x86
  - x64

version: '{build}'
clone_depth: 1
matrix:
  fast_finish: true

install:
  - ps: wget 'https://github.com/philsquared/Catch/archive/V1.5.0.tar.gz' -OutFile 'catch.tar.gz'
  - ps: 7z.exe x catch.tar.gz -oC:\catch

build: off

test_script:
  - cd test
  - ps: ls C:\
  - ps: ls C:\catch
  - ps: ls C:\catch\single_include
  - cmake -DCMAKE_INCLUDE_PATH=C:\catch\single_include . 
  - ps: make
  - ps: tests
