os: Visual Studio 2015
platform:
  - x86
  - x64

version: '{build}'
shallow_clone: true
matrix:
  fast_finish: true

install:
  - ps: wget 'https://github.com/philsquared/Catch/archive/V1.5.0.zip' -OutFile 'catch.zip'
  - ps: 7z.exe x catch.zip -oC:\

build: off

test_script:
  - cd test
  - cmake -DCMAKE_INCLUDE_PATH=C:\Catch-1.5.0\single_include . 
  - ls .
  - msbuild MantellaTests.sln
  - cmake --build .
  - tests
